package org.xmlquery;

import java.util.ArrayList;
import java.util.List;

/**
 * Contains a table of {@link XPathResultValue} objects. Generated by an {@link XPathExpressionProcessor}.
 *
 * @see XPathExpressionProcessor
 * @see XPathResultValue
 */
public class XPathResultValueTable
{
  private String tableName;
  private List<String> columnNames;
  private List<List<XPathResultValue>> rows;

  public XPathResultValueTable(String tableName)
  {
    this.rows = new ArrayList<>();
    this.tableName = tableName;
    this.columnNames = new ArrayList<>();
  }

  public XPathResultValueTable(String tableName, List<String> columnNames)
  {
    this.tableName = tableName;
    this.columnNames = columnNames;
    rows = new ArrayList<>();
  }

  public String getTableName()
  {
    return tableName;
  }

  public List<List<XPathResultValue>> getRows()
  {
    return rows;
  }

  public List<String> getColumnNames()
  {
    return columnNames;
  }

  public void setColumnNames(List<String> columnNames)
  {
    this.columnNames = columnNames;
  }

  public void addRow(List<XPathResultValue> row)
  {
    rows.add(row);
  }

  public boolean isEmpty()
  {
    return rows.isEmpty();
  }

  public void appendTable(XPathResultValueTable table)
  {
    rows.addAll(table.getRows());
  }

  public String toDebugString()
  {
    StringBuilder sb = new StringBuilder(getTableName() + "\n");

    sb.append(buildColumnNamesString());

    for (List<XPathResultValue> row : rows) {
      sb.append("[");
      boolean isFirstValue = true;
      for (XPathResultValue value : row) {
        if (!isFirstValue)
          sb.append(", ");
        sb.append(value);
        isFirstValue = false;
      }
      sb.append("]\n");
    }

    return sb.toString();
  }

  public String toString()
  {
    StringBuilder sb = new StringBuilder();

    sb.append(buildColumnNamesString());

    for (List<XPathResultValue> row : rows) {
      boolean isFirstValue = true;
      for (XPathResultValue value : row) {
        if (!isFirstValue)
          sb.append(", ");
        sb.append(value.getValue());
        isFirstValue = false;
      }
      sb.append("\n");
    }

    return sb.toString();
  }

  private String buildColumnNamesString()
  {
    StringBuilder sb = new StringBuilder();

    if (!columnNames.isEmpty()) {
      boolean isFirstValue = true;
      for (String columnName : columnNames) {
        if (!isFirstValue)
          sb.append(", ");
        sb.append(columnName);
        isFirstValue = false;
      }
      sb.append("\n");
    }
    return sb.toString();
  }
}
